apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gcp-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 5
    type: HTTP
    requestPath: /healthz
