apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "ingress-swiftnews"

spec:
  rules:
    # - host: api.localhost
      - http: 
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: apigateway-clusterip-srv
                port:
                  number: 80
