# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-for-mongo
#   labels:
#     type: local
# spec:
#   capacity:
#     storage: 500Mi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: "local-path"
#   hostPath:
#     path: /opt/local-path-provisioner
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - k3d-ruby-agent-0    

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongo-pvc
# spec:
#   storageClassName: "local-path"
#   accessModes:
#     - ReadWriteOnce 
#   resources:
#     requests:
#       storage: 500Mi

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-mongo
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: gke-pv
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
