apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-userservice-pg
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-path"
  hostPath:
    path: /opt/local-path-provisioner-userservice
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-ruby-agent-0
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-userservice-pvc
spec:
  storageClassName: "local-path"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
