version: '3.9'

services:
  likeservice:
    image: likeservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      MongoDbSettings__ConnectionString: "mongodb://mongouser:mongopassword@mongodb:27017"
      ASPNETCORE_ENVIRONMENT: Docker

    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
