name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI and SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
        
      - name: Configure Docker
        run: |
            gcloud --quiet auth configure-docker

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
    
      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.GKE_ZONE }}-docker.pkg.dev/${{secrets.GCP_PROJECT}}/swiftnews/apigateway:latest ./ApiGateway
          docker build -t ${{ secrets.GKE_ZONE }}-docker.pkg.dev/${{secrets.GCP_PROJECT}}/swiftnews/likeservice:latest ./LikeService
          docker build -t ${{ secrets.GKE_ZONE }}-docker.pkg.dev/${{secrets.GCP_PROJECT}}/swiftnews/postservice:latest ./PostService
          docker build -t ${{ secrets.GKE_ZONE }}-docker.pkg.dev/${{secrets.GCP_PROJECT}}/swiftnews/userservice:latest ./UserService
          docker push ${{ secrets.GKE_ZONE }}-docker.pkg.dev/${{secrets.GCP_PROJECT}}/swiftnews/apigateway:latest
          docker push ${{ secrets.GKE_ZONE }}-docker.pkg.dev/${{secrets.GCP_PROJECT}}/swiftnews/likeservice:latest
          docker push ${{ secrets.GKE_ZONE }}-docker.pkg.dev/${{secrets.GCP_PROJECT}}/swiftnews/postservice:latest
          docker push ${{ secrets.GKE_ZONE }}-docker.pkg.dev/${{secrets.GCP_PROJECT}}/swiftnews/userservice:latest
        
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f K8S/mongo-config.yaml
          kubectl apply -f K8S/mongo-secret.yaml
          kubectl apply -f K8S/mongo-pv-storage.yaml
          kubectl apply -f K8S/mongo-plat-depl.yaml
          kubectl apply -f K8S/postgres-pv-storage.yaml
          kubectl apply -f K8S/posts-np-srv.yaml
          kubcetl apply -f K8S/postgres-plat-depl.yaml
          kubectl apply -f K8S/postgres-userservice-pv.yaml
          kubectl apply -f K8S/postgres-userservice.yaml
          kubectl apply -f K8S/rabbitmq-depl.yaml
          kubectl apply -f K8S/posts-depl.yaml
          kubectl apply -f K8S/likes-depl.yaml
          kubectl apply -f K8S/posts-depl.yaml
          kubectl apply -f K8S/users-depl.yaml
          kubectl apply -f K8S/apigateway-depl.yaml
          kubectl apply -f K8S/ingress-srv.yaml
