name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for PostService
      run: dotnet restore ./PostService
    - name: Build PostService
      run: dotnet build ./PostService --no-restore
    - name: Test PostService
      run: dotnet test ./PostService --no-build --verbosity normal

    - name: Restore dependencies for LikeService
      run: dotnet restore ./LikeService
    - name: Build LikeService
      run: dotnet build ./LikeService --no-restore
    - name: Test LikeService
      run: dotnet test ./LikeService --no-build --verbosity normal
