name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies for PostService
        run: dotnet restore ./PostService
      - name: Build PostService
        run: dotnet build ./PostService --no-restore

      - name: Build and Push PostService Docker Image
        run: |
          docker build -t rubyfeller/postservice:latest ./PostService
          docker push rubyfeller/postservice:latest

      - name: Restore dependencies for LikeService
        run: dotnet restore ./LikeService
      - name: Build LikeService
        run: dotnet build ./LikeService --no-restore

      - name: Build and Push LikeService Docker Image
        run: |
          docker build -t rubyfeller/likeservice:latest ./LikeService
          docker push rubyfeller/likeservice:latest

      - name: Restore dependencies for UserService
        run: dotnet restore ./UserService
      - name: Build UserService
        run: dotnet build ./UserService --no-restore

      - name: Build and Push UserService Docker Image
        run: |
          docker build -t rubyfeller/userservice:latest ./UserService
          docker push rubyfeller/userservice:latest

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Test PostService
        run: dotnet test ./PostService --no-build --verbosity normal

      - name: Test LikeService
        run: dotnet test ./LikeService --no-build --verbosity normal

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: build
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
  
      - name: Check Docker version
        run: docker --version
  
      - name: Restore dependencies for Integration Tests
        run: dotnet restore ./IntegrationTests
      - name: Build Integration Tests
        run: dotnet build ./IntegrationTests --no-restore
      - name: Run Integration Tests
        run: dotnet test ./IntegrationTests --no-build --verbosity detailed || true
